settings:
  title: 'Status Page'
  url: 'https://statuswebqr.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: meinkiga-app-system # unique identifier
    name: my.meinkiga.app
    description: 'MeinKiGa System' # default=empty
    url: 'https://my.meinkiga.app/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: drkkita-app-system
    name: my.drk-kita.app
    url: 'https://my.drk-kita.app/'
    method: GET
    expectStatus: 200
    
  - id: mghapp-app-system
    name: my.mgh-app.de
    url: 'https://my.mgh-app.de/'
    method: GET
    expectStatus: 200
    
  - id: satello-app-system
    name: my.satello.app
    url: 'https://my.satello.app/'
    method: GET
    expectStatus: 200
