settings:
  title: 'webQR System Status'
  url: 'https://statuswebqr.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: main-app-system
    name: webQR Main System
    description: 'webQR Main System' # default=empty
    url: 'https://my.webqr.eu/'
    method: GET
    expectStatus: 200
    linkable: false
    
  - id: meinkiga-app-system # unique identifier
    name: MeinKiGa App
    url: 'https://my.meinkiga.app/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: drkkita-app-system
    name: DRK Kita App
    url: 'https://my.drk-kita.app/'
    method: GET
    expectStatus: 200
    linkable: false
    
  - id: mghapp-app-system
    name: MGH App
    url: 'https://my.mgh-app.de/'
    method: GET
    expectStatus: 200
    linkable: false
    
  - id: satello-app-system
    name: Satello App
    url: 'https://my.satello.app/'
    method: GET
    expectStatus: 200
    linkable: false
